version: '3'

services:

  api.getway:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api.user.0
      - api.user.1
      - api.user.2
      - front.admin
      - front.public


  front.public:
    build: ./frontend/public
    command: sh -c " npm install && npm start "
    volumes:
      - ./frontend/public/src:/usr/src/app  

  front.admin:
    container_name: front.admin
    build: ./frontend/admin
    command: sh -c " npm install && npm start "
    volumes:
      - ./frontend/admin/src:/usr/src/app


  api.user.0:
    build: ./backend/user
    command: sh -c " npm install && npm start "
    environment:
      - SERVER_NAME="Api Jonny"
    volumes:
      - ./backend/user/src:/usr/src/app

  api.user.1:
    build: ./backend/user
    command: sh -c " npm install && npm start "
    volumes:
      - ./backend/user/src:/usr/src/app
    environment:
      - SERVER_NAME="Api Sunny"

  api.user.2:
    build: ./backend/user
    command: sh -c " npm install && npm start "
    volumes:
      - ./backend/user/src:/usr/src/app
    environment:
      - SERVER_NAME="Api Funny"
